---
# tasks file for nodejs
- name: nodejs Installation
  get_url:
    url: https://deb.nodesource.com/setup_14.x
    dest: /home/vagrant/nodesource_install_script
  register: download_nodejs_script
- name: Run the installation script
  become: true
  command: bash /home/vagrant/nodesource_install_script
  when: download_nodejs_script.changed
- name: Make sure NodeJS is installed
  become: true
  package:
    name: nodejs
